variables:
  IMAGE_PIPELINE_RUNNER: docker:22.06.0-beta.0-cli
  DOCKER_HOST: tcp://dind-service:2375
stages:
  - test

.install_make: &install_make
  - apt update && apt install -y make

.compose_pull_start: &compose_pull_start
  - sh -c "cd ${COMPOSE_FOLDER} && docker-compose -p $COMPOSE_ID -f $COMPOSE_FILE pull db redis"
  - sh -c "cd ${COMPOSE_FOLDER} && docker-compose -p $COMPOSE_ID -f $COMPOSE_FILE up -d db redis"
  - sleep 3

.compose_over: &compose_over
  - sh -c "cd ${COMPOSE_FOLDER} && docker-compose -p $COMPOSE_ID down --volumes --rmi local"

.job_compose: &job_compose
  before_script:
    - *install_make
    - *compose_pull_start
  after_script:
    - *compose_over

build-test-django:
  image: ${IMAGE_PIPELINE_RUNNER}
  stage: test
  variables:
    COMPOSE_ID: ${CI_PIPELINE_ID}_django
    COMPOSE_FILE: docker-compose.dev.yml
    COMPOSE_FOLDER: example_frm_django
  <<: *job_compose
  script:
    - sh -c "cd ${COMPOSE_FOLDER} && make dev_build"
    - sh -c "cd ${COMPOSE_FOLDER} && make dev_test"

build-test-fastapi:
  image: ${IMAGE_PIPELINE_RUNNER}
  stage: test
  variables:
    COMPOSE_ID: ${CI_PIPELINE_ID}_fastapi
    COMPOSE_FILE: docker-compose.dev.yml
    COMPOSE_FOLDER: example_frm_fastapi
  <<: *job_compose
  script:
    - sh -c "cd ${COMPOSE_FOLDER} && make dev_build"
    - sh -c "cd ${COMPOSE_FOLDER} && make dev_test"
