variables:
  IMAGE_PIPELINE_RUNNER: docker:22.06.0-beta.0-cli
  DOCKER_HOST: tcp://dind-service:2375

stages:
  - test

.install_task: &install_task
  - apk update && apk add curl
  - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

.setup: &setup
  before_script:
    - *install_task

build-test-django:
  image: ${IMAGE_PIPELINE_RUNNER}
  stage: test
  variables:
    COMPOSE_ID: ${CI_PIPELINE_ID}_django
  <<: *setup
  script:
    - cd example_frm_django
    - task dev:test

build-test-fastapi:
  image: ${IMAGE_PIPELINE_RUNNER}
  stage: test
  variables:
    COMPOSE_ID: ${CI_PIPELINE_ID}_fastapi
  <<: *setup
  script:
    - cd example_frm_fastapi
    - task dev:test
