variables:
  IMAGE_PIPELINE_RUNNER: docker:22.06.0-beta.0-cli
  # dind
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - test

.setup: &setup
  before_script:
    - apk update && apk add curl
    - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
    - ./docker/wait-for-command.sh -c 'curl docker:2375' -t 30
  services:
    - name: docker:22.06.0-beta.0-dind
      alias: docker

build-test-django:
  image: ${IMAGE_PIPELINE_RUNNER}
  stage: test
  <<: *setup
  variables:
    COMPOSE_ID: ${CI_PIPELINE_ID}_django
  script:
    - cd example_frm_django
    - task dev:test

build-test-fastapi:
  image: ${IMAGE_PIPELINE_RUNNER}
  stage: test
  variables:
    COMPOSE_ID: ${CI_PIPELINE_ID}_fastapi
  <<: *setup
  script:
    - cd example_frm_fastapi
    - task dev:test
