version: '3'

tasks:
  down:
    internal: true
    cmds:
      - docker-compose -f {{.COMPOSE_FILE}} -p {{.COMPOSE_ID}} down
    dir: ./{{.DIR}}

  build:
    internal: true
    cmds:
      - docker-compose -f {{.COMPOSE_FILE}} -p {{.COMPOSE_ID}} build -- web
      - docker-compose -f {{.COMPOSE_FILE}} -p {{.COMPOSE_ID}} build 
    dir: ./{{.DIR}}

  up:
    internal: true
    cmds:
      - task: build
      - defer: { task: down }
      - docker-compose -f {{.COMPOSE_FILE}} -p {{.COMPOSE_ID}} up
    dir: ./{{.DIR}}

  run:
    internal: true
    cmds:
      - task: build
      - defer: { task: down }
      - docker-compose -f {{.COMPOSE_FILE}} -p {{.COMPOSE_ID}} run {{.CMD}}
    dir: ./{{.DIR}}

  ci_run:
    internal: true
    cmds:
      - defer: docker-compose -f {{.COMPOSE_FILE}} -p {{.COMPOSE_ID}} down --volumes --rmi local
      - task: build
      - docker-compose -p {{.COMPOSE_ID}} -f {{.COMPOSE_FILE}} pull {{.PULL_CONTAINERS}}
      - docker-compose -p {{.COMPOSE_ID}} -f {{.COMPOSE_FILE}} up -d {{.PULL_CONTAINERS}}
      - sleep 3
      - docker-compose -f {{.COMPOSE_FILE}} -p {{.COMPOSE_ID}} run {{.CMD}}
    dir: ./{{.DIR}}

      