x-services:
  app_poetry: &app_poetry
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      DJANGO_DEBUG: "true"

version: '3.8'
services:
  db:
    image: postgres:15 # 5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgres
  redis:
    image: redis # 6379
  job_migrate:
    <<: *app_poetry
    command: python manage.py migrate
  web:
    <<: *app_poetry
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - job_migrate

