name: Build

on:
  pull_request: {}
  push:
    branches: ["master"]
    
jobs:
  build-test-django:
    name: Build and test Django
    runs-on: self-hosted
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - uses: ./.github/actions/cleanup-docker
      - name: Build image
        run: make dev_build
        working-directory: example_frm_django
      - uses: ./.github/actions/compose-pull-start
        with:
          docker-compose: docker-compose.dev.yml
          containers: db redis
          workdir: example_frm_django
      - name: Test image
        run: make dev_test
        working-directory: example_frm_django

  build-test-fastapi:
    name: Build and test FastAPI
    runs-on: self-hosted
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - uses: ./.github/actions/cleanup-docker
      - name: Build image
        run: make dev_build
        working-directory: example_frm_fastapi
      - uses: ./.github/actions/compose-pull-start
        with:
          docker-compose: docker-compose.dev.yml
          containers: db redis
          workdir: example_frm_fastapi
      - name: Test image
        run: make dev_test
        working-directory: example_frm_fastapi
          

