name: Build

on:
  pull_request: {}
  push:
    branches: ["master"]
    
jobs:
  build-test-django:
    name: Build and test Django
    runs-on: self-hosted
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - uses: ./.github/actions/cleanup-docker
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Test
        run: COMPOSE_ID=${{ github.run_id }}_django task dev:test
        working-directory: example_frm_django

  build-test-fastapi:
    name: Build and test FastAPI
    runs-on: self-hosted
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - uses: ./.github/actions/cleanup-docker
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Test
        run: COMPOSE_ID=${{ github.run_id }}_fastapi task dev:ci_test
        working-directory: example_frm_fastapi
          

